name: fpl-app
dependencies:
  - python=3.9
  - ipython==8.13.2
  - ipykernel==6.23.1
  - ipywidgets==8.0.6
  - jinja2==3.1.2
  - numpy>=1.25.2
  - streamlit>=1.24.1
  - pip>=22.3.1
  - plotly::plotly==5.16.1
  - pip:
    - FPL-data-loader>=0.0.9